export const properties = [
  {
    id: 1,
    property_type: "Single Family Home",
    listing_price: 500000,
    bedrooms: 3,
    bathrooms: 2,
    square_footage: 1800,
    location: "City A",
    year_built: 2005,
    garage_size: "2-car",
    image_url: "https://example.com/images/property1.jpg",
    listing_name: "Spacious Family Home in City A",
  },
  {
    id: 2,
    property_type: "Condominium",
    listing_price: 350000,
    bedrooms: 2,
    bathrooms: 2,
    square_footage: 1200,
    location: "City B",
    year_built: 2010,
    garage_size: "1-car",
    image_url: "https://example.com/images/property2.jpg",
    listing_name: "Modern Condo in City B",
  },
  {
    id: 3,
    property_type: "Townhouse",
    listing_price: 400000,
    bedrooms: 4,
    bathrooms: 3,
    square_footage: 2200,
    location: "City C",
    year_built: 2012,
    garage_size: "2-car",
    image_url: "https://example.com/images/property3.jpg",
    listing_name: "Contemporary Townhouse in City C",
  },
  {
    id: 4,
    property_type: "Single Family Home",
    listing_price: 600000,
    bedrooms: 4,
    bathrooms: 3.5,
    square_footage: 2500,
    location: "City A",
    year_built: 1998,
    garage_size: "3-car",
    image_url: "https://example.com/images/property4.jpg",
    listing_name: "Charming Home with Large Yard in City A",
  },
  {
    id: 5,
    property_type: "Apartment",
    listing_price: 200000,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 800,
    location: "City B",
    year_built: 1980,
    garage_size: "No garage",
    image_url: "https://example.com/images/property5.jpg",
    listing_name: "Cozy Apartment in City B",
  },
  {
    id: 6,
    property_type: "Single Family Home",
    listing_price: 700000,
    bedrooms: 5,
    bathrooms: 4,
    square_footage: 3200,
    location: "City C",
    year_built: 2018,
    garage_size: "2-car",
    image_url: "https://example.com/images/property6.jpg",
    listing_name: "Luxurious Home with Modern Amenities in City C",
  },
  {
    id: 7,
    property_type: "Condominium",
    listing_price: 300000,
    bedrooms: 2,
    bathrooms: 1.5,
    square_footage: 1000,
    location: "City A",
    year_built: 2007,
    garage_size: "1-car",
    image_url: "https://example.com/images/property8.jpg",
    listing_name: "Modern Condo with City Views in City A",
  },
  {
    id: 8,
    property_type: "Single Family Home",
    listing_price: 750000,
    bedrooms: 4,
    bathrooms: 3.5,
    square_footage: 2800,
    location: "City B",
    year_built: 2013,
    garage_size: "2-car",
    image_url: "https://example.com/images/property9.jpg",
    listing_name: "Stunning Home with Outdoor Pool in City B",
  },
  {
    id: 9,
    property_type: "Condominium",
    listing_price: 250000,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 900,
    location: "City C",
    year_built: 2008,
    garage_size: "No garage",
    image_url: "https://example.com/images/property10.jpg",
    listing_name: "Cozy Condo in Quiet Neighborhood in City C",
  },
  {
    id: 10,
    property_type: "Townhouse",
    listing_price: 550000,
    bedrooms: 3,
    bathrooms: 2.5,
    square_footage: 2000,
    location: "City B",
    year_built: 2015,
    garage_size: "2-car",
    image_url: "https://example.com/images/property11.jpg",
    listing_name: "Modern Townhouse with Rooftop Terrace in City B",
  },
  {
    id: 11,
    property_type: "Single Family Home",
    listing_price: 800000,
    bedrooms: 4,
    bathrooms: 3.5,
    square_footage: 3000,
    location: "City A",
    year_built: 2010,
    garage_size: "3-car",
    image_url: "https://example.com/images/property12.jpg",
    listing_name: "Elegant Home with Spacious Interiors in City A",
  },
  {
    id: 12,
    property_type: "Apartment",
    listing_price: 180000,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 700,
    location: "City C",
    year_built: 1995,
    garage_size: "No garage",
    image_url: "https://example.com/images/property13.jpg",
    listing_name: "Affordable Apartment in Convenient Location in City C",
  },
  {
    id: 13,
    property_type: "Single Family Home",
    listing_price: 650000,
    bedrooms: 3,
    bathrooms: 2.5,
    square_footage: 2200,
    location: "City A",
    year_built: 2009,
    garage_size: "2-car",
    image_url: "https://example.com/images/property15.jpg",
    listing_name: "Coastal Home with Ocean Views in City A",
  },
  {
    id: 14,
    property_type: "Condominium",
    listing_price: 400000,
    bedrooms: 2,
    bathrooms: 2,
    square_footage: 1100,
    location: "City B",
    year_built: 2016,
    garage_size: "1-car",
    image_url: "https://example.com/images/property16.jpg",
    listing_name: "Modern Condo near Downtown in City B",
  },
  {
    id: 15,
    property_type: "Townhouse",
    listing_price: 380000,
    bedrooms: 3,
    bathrooms: 2.5,
    square_footage: 1800,
    location: "City C",
    year_built: 2014,
    garage_size: "2-car",
    image_url: "https://example.com/images/property17.jpg",
    listing_name: "Spacious Townhouse with Private Patio in City C",
  },
  {
    id: 16,
    property_type: "Single Family Home",
    listing_price: 950000,
    bedrooms: 5,
    bathrooms: 4.5,
    square_footage: 3500,
    location: "City A",
    year_built: 2012,
    garage_size: "3-car",
    image_url: "https://example.com/images/property18.jpg",
    listing_name: "Luxury Home with Home Theater in City A",
  },
  {
    id: 17,
    property_type: "Apartment",
    listing_price: 220000,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 850,
    location: "City B",
    year_built: 2006,
    garage_size: "No garage",
    image_url: "https://example.com/images/property19.jpg",
    listing_name: "Renovated Apartment with Modern Finishes in City B",
  },
  {
    id: 18,
    property_type: "Single Family Home",
    listing_price: 720000,
    bedrooms: 4,
    bathrooms: 3.5,
    square_footage: 2800,
    location: "City C",
    year_built: 2011,
    garage_size: "2-car",
    image_url: "https://example.com/images/property20.jpg",
    listing_name: "Spacious Home with Mountain Views in City C",
  },
  {
    id: 19,
    property_type: "Condominium",
    listing_price: 380000,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 750,
    location: "City A",
    year_built: 2009,
    garage_size: "1-car",
    image_url: "https://example.com/images/property21.jpg",
    listing_name: "Charming Condo in the Heart of City A",
  },
  {
    id: 20,
    property_type: "Townhouse",
    listing_price: 520000,
    bedrooms: 3,
    bathrooms: 2.5,
    square_footage: 1900,
    location: "City B",
    year_built: 2013,
    garage_size: "2-car",
    image_url: "https://example.com/images/property22.jpg",
    listing_name: "Modern Townhouse with Open Floor Plan in City B",
  },
];
